name: Windows_Pester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'Pester' -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run tests
      env:
        TestAPIUser: ${{ secrets.TestAPIUser }}
        TestAPIPw: ${{ secrets.TestAPIPw }}
      run: Invoke-Pester -Path '.\tests'
      shell: pwsh